spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:weather
    username: sa
    password:
  h2:
    console:
      enabled: true

